Adding switch case and reusable function
IBM/sol005-lifecycle-driver pull request #89
Opened 2022-09-22 05:26 UTC by rkumar8j

#88
Add switch case and reusable functions 
Signed-off-by: rkumar8j (mailto:rkumar8j@in.ibm.com)

2022-09-22 06:05 UTC, lokanalla requested changes

2022-09-22 06:05 UTC, lokanalla commented on src/main/java/com/ibm/nfvodriver/service/LifecycleManagementService.java
> -                final String createNsRequest = messageConversionService.generateMessageFromRequest("CreateNsRequest", executionRequest);
generateMessageFromRequest method call is there in all cases, can't we keep ahead of having switch and pass the 1st parameter based on the lifecycle, fetch the real value from a map.

2022-09-26 10:07 UTC, lokanalla commented on src/main/java/com/ibm/nfvodriver/service/LifecycleManagementService.java
> +    private final Map requestTypeMap = Map.of(LIFECYCLE_CREATE,"CreateNsRequest",
Missing for Delete lifecycle

2022-09-26 10:11 UTC, lokanalla commented on src/main/java/com/ibm/nfvodriver/service/LifecycleManagementService.java
> +        if(requestTypeMap.containsKey(lifecycleName))
Put an else condition and throw an exception saying not supported lifecycle name.

2022-09-26 10:12 UTC, lokanalla commented on src/main/java/com/ibm/nfvodriver/service/LifecycleManagementService.java
> +                    throw new IllegalArgumentException(String.format("Requested transition [%s] is not supported by this lifecycle driver", executionRequest.getLifecycleName()));
As this exception is already handled in else block above, This can be a driver error.

2022-09-26 10:21 UTC, rkumar8j commented on src/main/java/com/ibm/nfvodriver/service/LifecycleManagementService.java
> +    private final Map requestTypeMap = Map.of(LIFECYCLE_CREATE,"CreateNsRequest",
delete lifecycle doesn't need payload

2022-09-26 10:30 UTC, lokanalla approved these changes

2022-09-27 04:54 UTC, HariKrishna1-ibm approved these changes

2022-09-27 04:55 UTC, merged